OPTIM:
  NAME: "adamw"
  LR: [0.0001, 0.00001, 0.000001, 0.0000001]
  WEIGHT_DECAY: [0.0, 0.001, 0.00001]
  LR_SCHEDULER: 'cosine'
  BATCH_SIZE: [8]
  MAX_ITER: [12800]
  WARMUP_ITER: 50
  WARMUP_TYPE: "linear"
  WARMUP_MIN_LR: 1e-5