OPTIM:
  NAME: "sgd"
  SGD_NESTEROV: False
  LR: [50, 30, 10, 3, 1, 0.1,]
  WEIGHT_DECAY: [0.0, 0.01, 0.0001, 0.000001]
  LR_SCHEDULER: 'cosine'
  BATCH_SIZE: [8, 32]
  MAX_ITER: [12800]
  WARMUP_ITER: 50
  WARMUP_TYPE: "linear"
  WARMUP_MIN_LR: 1e-5