FEATURE:
  NAME: "rn50_view_100_rcrop_template_single"
  VIEWS_PER_TRAIN: 100
  VIEWS_PER_VAL: 1
  LAYER_IDX: 0
  TEMPLATE: "single"

INPUT:
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE: "RN50"