FEATURE:
  NAME: "vitb16_view_1_ccrop_template_classname"
  VIEWS_PER_TRAIN: 1
  VIEWS_PER_VAL: 1
  LAYER_IDX: 0
  TEMPLATE: "classname"

INPUT:
  TRANSFORMS: ["center_crop", "normalize"]

MODEL:
  BACKBONE: "ViT-B/16"