FEATURE:
  NAME: "vitb16_view_100_valview_100_rcrop_template_extra"
  VIEWS_PER_TRAIN: 100
  VIEWS_PER_VAL: 100
  LAYER_IDX: 0
  TEMPLATE: "extra"

INPUT:
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE: "ViT-B/16"