ENSEMBLE_SAME_TEMPLATES = [
    "This is a photo of a {}.",
    "a photo of a nice {}.",
    "That is a photo of a {}.",
    "a good photo of a {}.",
    "a photo of the nice {}.",
    "a photo of the weird {}.",
    "a picture of an {}.",
    "a cropped photo of the {}.",
    "a picture of a {}.",
    "a cropped photo of a {}.",
    "a photo of the {}.",
    "a photo of a weird {}.",
    "a photo of the large {}.",
    "a photo of an {}.",
    "a bad photo of a {}.",
    "a photo of those {}.",
    "a photo of the small {}.",
    "a photo of a {}.",
]